%% Instructions
%Change directory (file_location)
%Change name variable such that it picks up the name of the file
%Change the control wells (no Dox/-ve,+ve controls) starting at line 41
%Change fake outlier index variable (exclude some data manually during hit identification) LINE 197 depending on how the graph looks (line 198)
%Use Task Mnaager to close Excel if any error in editing files, also delete and close excel files before running
%Get rid of other excel files other than masks mCherry if it shows
%datastore something error, get rid of extra columns in masks sheet as well
%if error continues
%%
clc;
clear;
close all 

file_location= '\\everest\jain_imaging\Pushkal\20250112_Sensor_temporal_Confocal\Analysis\';



D = dir([file_location, '\*.csv']); %Put directory of the excel files generated by CellProfiler (Step 2.m)
filenames = {D(:).name}.';
data = cell(length(D),1);
for ii = 1:1:length(D)
      % Create the full file name and partial filename
      fullname = [file_location D(ii).name];
      % Read in the data
      data{ii} = {readall(tabularTextDatastore(fullname,'FileExtensions','.csv'))};         
end

%Extract the name of the excel file from the directory
 name = extractAfter(fullname,"Pushkal\");   %Put the stuff just before folder name
 name = extractBefore(name,"\MyExpt");
 path=extractBefore(fullname,"MyExpt");
 
%% Calculation of YFP/mCherry ratio at single-cell level for each well  
   index=find(contains(filenames,'Masks_mCherry'));    % Use Masks_CellPose.csv which contains measured data for all cytoplasm masks 
   data_for_each_image=data{index,1}{1,1};  %Takes cell level information
   
   well_unique=unique(data_for_each_image.Metadata_Well);
   

for j=1:length(well_unique)    
    
     index=find(contains(data_for_each_image.Metadata_Well,well_unique(j)));  %Find indices of particular well in the CellPose masks 
     
     FS{j}= data_for_each_image.Intensity_IntegratedIntensity_YFP_without_foci(index)./data_for_each_image.Intensity_IntegratedIntensity_mCherry_without_foci(index); 
     mean_YFP{j}= data_for_each_image.Intensity_IntegratedIntensity_YFP_without_foci(index)./data_for_each_image.AreaShape_Area(index); 
     mean_mCherry{j}= data_for_each_image.Intensity_IntegratedIntensity_mCherry_without_foci(index)./data_for_each_image.AreaShape_Area(index); 
     area{j}=data_for_each_image.AreaShape_Area(index); 
    
     %FS is a cell whose element contains FS ratios for a particular well except no Dox control    
     %mean_YFP and mean_mCherry are cells whose each element contains channel signal per unit area of cells
     
     %Get rid of too small or too big segmentations, assuming they are not
     %biological objects
     area_max_cutoff=quantile(area{1,j},0.75)+3*iqr(area{1,j}); 
     area_min_cutoff=quantile(area{1,j},0.25)-3*iqr(area{1,j}); 
%      FS_max_cutoff=quantile(FS{1,j},0.75)+3*iqr(FS{1,j});
%      FS_min_cutoff=quantile(FS{1,j},0.25)-3*iqr(FS{1,j});

% Remove too high and too dim mCherry, likely takes care of overexposed or
% uninduced cells
% cells
     mCherry_max_cutoff=quantile(mean_mCherry{1,j},0.75)+3*iqr(mean_mCherry{1,j}); 
     mCherry_min_cutoff=quantile(mean_mCherry{1,j},0.25)-3*iqr(mean_mCherry{1,j}); 
 
     
     index_null1=find(area{1,j}<area_min_cutoff); 
     index_null4=find(area{1,j}>area_max_cutoff); 
%       index_null5=find(FS{1,j}<FS_min_cutoff);
%       index_null6=find(FS{1,j}>FS_max_cutoff);

%index_null2=find(mean_mCherry{1,j}<mCherry_min_cutoff);
%index_null3=find(mean_mCherry{1,j}>mCherry_max_cutoff); 


     index_null=[index_null1;index_null4]; 
          
     FS{1,j}(index_null)=[];  %get rid of FS ratios for cells      
     mean_YFP{1,j}(index_null)=[];  
     mean_mCherry{1,j}(index_null)=[];  
     area{1,j}(index_null)=[]; 
     
%Take median of the all cells in each well 
     FSratio(j)=nanmedian(FS{1,j}(:));
     FSratio_std(j)=mad(FS{1,j}(:),1);
     YFPm(j)=median(mean_YFP{1,j}(:));
     YFPm_std(j)=mad(mean_YFP{1,j}(:),1);
     mCherrym(j)=median(mean_mCherry{1,j}(:));
     mCherrym_std(j)=mad(mean_mCherry{1,j}(:),1);
     area_median(j)=median(area{1,j}(:));  %do not account for <2000 pixel CellPose masks 
     sample_size_each_well(j)=length(index)-length(index_null); %total number of cells in each well whose median is being reported  
     
end

%%Plotting 
name=strrep(name,'_',' '); 
errorbar(1:length(well_unique),FSratio, FSratio_std,'vertical','o');
title(['FS Ratios - ' name]);
text(1:length(FSratio), FSratio+0.02, well_unique);
figure();

scatter(1:length(well_unique),YFPm);
title(['Mean YFP - ' name]);
text(1:length(YFPm), YFPm, well_unique);
figure();

scatter(1:length(well_unique),mCherrym);
title(['Mean mCherry - ' name]);
text(1:length(mCherrym), mCherrym, well_unique);
figure();


scatter(mCherrym,YFPm);
text(mCherrym, YFPm, well_unique);
title(['YFP vs mCherry ' name]);


     

















%Make a matrix
% FS_matrix=(reshape(FSratio,[Ncol-1 Nrow]))'; %make a matrix of the FS ratios except column 2 
% cell_number_matrix=(reshape(number_of_cells,[Ncol-1 Nrow]))';
% mYFP_matrix=(reshape(YFPm,[Ncol-1 Nrow]))';
% mmCherry_matrix=(reshape(mCherrym,[Ncol-1 Nrow]))';


%% Mito-toxin plate arrangement 
% Mito_FSmatrix=NaN(8,12);
% Mito_Cell_number=NaN(8,12); 
% 
% Mito_FSmatrix(2,3:11)=FSratio(1:9); 
% Mito_Cell_number(2,3:11)=number_of_cells(1:9);
% Mito_FSmatrix(3,3:11)=FSratio(10:18); 
% Mito_Cell_number(3,3:11)=number_of_cells(10:18);
% Mito_FSmatrix(4,3:11)=FSratio(19:27); 
% Mito_Cell_number(4,3:11)=number_of_cells(19:27);
% 
% % Mito_FSmatrix(2,3:8)=FSratio(1:6); 
% % Mito_Cell_number(2,3:8)=number_of_cells(1:6);
% % Mito_FSmatrix(3,3:9)=FSratio(8:14); 
% % Mito_Cell_number(3,3:9)=number_of_cells(8:14);
% % Mito_FSmatrix(4,3:9)=FSratio(16:22); 
% % Mito_Cell_number(4,3:9)=number_of_cells(16:22);
% % Mito_FSmatrix(5,3:9)=FSratio(24:30);
% % Mito_Cell_number(5,3:9)=number_of_cells(24:30);
% % Mito_FSmatrix(6,3:9)=FSratio(32:38); 
% % Mito_Cell_number(6,3:9)=number_of_cells(32:38); 
% % Mito_FSmatrix(7,3:9)=FSratio(40:46); 
% % Mito_Cell_number(7,3:9)=number_of_cells(40:46); 
% % Mito_FSmatrix(2:7,11)=FSratio([7,15,23,31,39,47]); 
% % Mito_Cell_number(2:7,11)=number_of_cells([7,15,23,31,39,47]);  
% 
% xvalues = {'1','2','3','4','5','6','7','8','9','10','11','12'}; %Column 2 and 11 have been removed
% yvalues = {'A','B','C','D','E','F','G','H'};
% h=heatmap(xvalues,yvalues,Mito_FSmatrix,'ColorLimits',[0.6 1.5]);
% name=strrep(name,'_',' '); 
% h.Title=['FS Ratio - ' name];
% h.Colormap=turbo;
% figure();
% h=heatmap(xvalues,yvalues,Mito_Cell_number,'ColorLimits',[0 4000]);
% name=strrep(name,'_',' '); 
% h.Title=['Cell number - ' name];
% h.Colormap=turbo;
% 


%%
% FS_matrix=(reshape(FSratio,[Ncol-1 Nrow]))'; %make a matrix of the FS ratios except column 2 
% cell_number_matrix=(reshape(number_of_cells,[Ncol-1 Nrow]))';
% mYFP_matrix=(reshape(YFPm,[Ncol-1 Nrow]))';
% mmCherry_matrix=(reshape(mCherrym,[Ncol-1 Nrow]))';

% %% Normalized FS ratio matrix
% FS_ratio_control=median((FS_matrix(:,end))); %the median of the negative control FS ratios (no systematic error correction) 
% 
% FS_matrix(:,end)=[]; %get rid of last control column, leaves Ncol-4 and Nrow-2 (Ncol/Nrow here being total rows/column in a commercial plate)
% cell_number_matrix(:,end)=[]; 
% mYFP_matrix(:,end)=[]; 
% mmCherry_matrix(:,end)=[]; 
% 
% %Skewness calculation
% skew_FSratio=skewness(FS_matrix,1,'all')
% skew_logFSratio=skewness(log2(FS_matrix),1,'all')
% skew_cell_number=skewness(cell_number_matrix,1,'all')
% skew_logcell_number=skewness(log2(cell_number_matrix),1,'all')
% skew_mYFP=skewness(mYFP_matrix,1,'all')
% skew_logmYFP=skewness(log2(mYFP_matrix),1,'all')
% skew_mmCherry= skewness(mmCherry_matrix,1,'all')
% skew_logmmCherry= skewness(log2(mmCherry_matrix),1,'all')
% 
% i1=find(contains(well_unique,'B11'));
% i2=find(contains(well_unique,'C11'));
% i3=find(contains(well_unique,'D11'));
% i4=find(contains(well_unique,'E11'));
% i5=find(contains(well_unique,'F11'));
% i6=find(contains(well_unique,'G11'));
% i=[i1 i2 i3 i4 i5 i6];
% well_unique(i)=[]; %get rid of last control column
% 
% cell_number_matrix=log2(cell_number_matrix); % log transformation of cell number matrix 
% cell_number_matrix=(cell_number_matrix-median(cell_number_matrix,'all'))/mad(cell_number_matrix,1,'all'); %check if >-2 MAD assuming the whole plate is control
% FS_matrix=FS_matrix-FS_ratio_control; % negative control subtraction as a normalization for FS ratio

% %Save FS ratio matrix in a csv file for analysis in R 
% writematrix(FS_matrix,[path,name,'input.csv']); 
% writematrix(cell_number_matrix,[path,name,'_cell_number.csv']); 

% %%
% %Two-way median polish on "FS ratio" matrix, (assuming random plating, after removing control columns) 
% [a,b,c,d,e]=median_polish(FS_matrix);
% B_Score=a/mad(a,1,'all'); 
% xvalues = {'3','4','5','6','7','8','9','10'}; %Column 2 and 11 have been removed
% yvalues = {'B','C','D','E','F','G'};
% h=heatmap(xvalues,yvalues,B_Score,'ColorLimits',[-5 5]);
% name=strrep(name,'_',' '); 
% h.Title=['B score - ' name];
% h.Colormap=turbo;
% figure();
% h=heatmap(xvalues,yvalues,cell_number_matrix,'ColorLimits',[-5 5]);
% name=strrep(name,'_',' '); 
% h.Title=['Cell number - ' name];
% h.Colormap=turbo;
% figure(); 


%%
% %LOESS residual calculation on FS_matrix
% noisy_data=[1:length(well_unique);reshape(FS_matrix',1,[])]';
% smoothed_data=fLOESS(noisy_data,0.1);
% residuals_LOESS=(noisy_data(:,2)-smoothed_data);
% Zscore_LOESS=(residuals_LOESS-median(residuals_LOESS))/mad(residuals_LOESS,1); 
% Zscore_LOESS=(reshape(Zscore_LOESS,[Ncol-2 Nrow]))';
% figure();
% h=heatmap(xvalues,yvalues,Zscore_LOESS,'ColorLimits',[-5 5]);
% name=strrep(name,'_',' '); 
% h.Title=['Loess - ' name];
% h.Colormap=turbo;

% %% Polish signal from individual channels followed by calculation of FS ratio
% %No in-plate control normalization 
% [a,b,c,d,e]=median_polish(mYFP_matrix);
% YFP_corrected_polish=a+b;
% [a,b,c,d,e]=median_polish(mmCherry_matrix);
% mCherry_corrected_polish=a+b;
% FS_corrected_polish=(YFP_corrected_polish./mCherry_corrected_polish);
% 
% skew_FS_corrected_polish= skewness(FS_corrected_polish,0,'all')
% skew_log_FS_corrected_polish= skewness(log2(FS_corrected_polish),0,'all')
% 
% Z_score=(FS_corrected_polish-median(FS_corrected_polish,'all'))/mad(FS_corrected_polish,1,'all'); %assuming whole plate is the control 
% figure();
% h=heatmap(xvalues,yvalues,Z_score,'ColorLimits',[-5 5]);
% name=strrep(name,'_',' '); 
% h.Title=['Polished Z score - ' name];
% h.Colormap=turbo;

%% Functions

function Results=normalitytest(x)
% This function calculates p-values for ten well-known normality tests and gives the results both on display and as a matrix.
% Included tests are:Kolmogorov-Smirnov test (Limiting form (KS-Lim), Stephens Method (KS-S), Marsaglia Method  (KS-M), Lilliefors test (KS-L)), Anderson-Darling (AD) test, Cramer-Von Mises (CvM) test, Shapiro-Wilk (SW) test, Shapiro-Francia (SF) test, Jarque-Bera (JB) test, D?gostino and Pearson (DAP) test.
  
% Enter the data as a row vector in the workspace
% Most tests run for n<900.
 
% example1: Normally distributed data
% x1=[66 53 154 76 73 118 106 69 87 84 41 33 78 56 55 35 44 135 75 58];
 
% example1: Disturbed data
% x2=[66 253 154 276 73 118 106 69 87 84 41 33 78 56 55 35 44 135 75 58];
 
% Alpha value can be changed as required
alpha=0.05;
% Please cite this work as: 
% ?ner, M., & Deveci Kocako?, ?. (2017). JMASM 49: A Compilation of Some Popular Goodness of Fit Tests for Normal Distribution: Their Algorithms and MATLAB Codes (MATLAB). Journal of Modern Applied Statistical Methods, 16(2), 30. 
% Copyright (c) (2016) ?ner, M., Deveci Kocakoc, I.
 
% KOLMOGOROV-SMIRNOV TEST- LIMITING FORM
 
n=length(x);
i=1:n;
y=sort(x);
fx=normcdf(zscore(y));
dplus=max(abs(fx-i/n));
dminus=max(abs(fx-(i-1)/n));
Dn=max(dplus,dminus);
KSz=sqrt(n)*Dn;
s=-20:1:20;
a=(-1).^s.*exp(-2*(s.*KSz).^2); 
pvalue=1-sum(a);
Results(1,1)=KSz;
Results(1,2)=pvalue;
 
% KOLMOGOROV-SMIRNOV TEST - STEPHENS MODIFICATION
 
dKSz=Dn*(sqrt(n)-0.01+0.85/sqrt(n));
 
if dKSz<0.775
    pvalue=0.15;
elseif dKSz<0.819
    pvalue=((0.10-0.15)/(0.819-0.775))*(dKSz-0.775)+0.15;
elseif dKSz<0.895
    pvalue=((0.05-0.10)/(0.895-0.819))*(dKSz-0.819)+0.10;
elseif dKSz<0.995
    pvalue=((0.025-0.05)/(0.995-0.895))*(dKSz-0.895)+0.05;
elseif dKSz<1.035
    pvalue=((0.01-0.025)/(1.035-0.995))*(dKSz-0.995)+0.025;
else
    pvalue=0.01;
end
Results(2,1)=dKSz;
Results(2,2)=pvalue;
 
% KOLMOGOROV-SMIRNOV TEST - MARSAGLIA METHOD
 
k=ceil(n*Dn);
m=2*k-1;
h=k-n*Dn;
 
Hmatrix=zeros(m,m);
 
for i=1:m-1
   for j=2:m
      if i-j+1>=0
      Hmatrix(i,j)=1/factorial(i-j+1);
    else
      Hmatrix(i,j)=0;
    end
    end
end
 
for i=1:m-1
    Hmatrix(i,1)=(1-h^i)/factorial(i);
end
 
Hmatrix(m,:)=fliplr(Hmatrix(:,1)');
 
if h<=0.5
Hmatrix(m,1)=(1 - 2*h^m)/factorial(m);
else
Hmatrix(m,1)=(1 - 2*h^m + max(0,2*h-1)^m)/factorial(m);
end
    lmax = max(eig(Hmatrix));
    Hmatrix = (Hmatrix./lmax)^n;
    pvalue = (1 - exp(gammaln(n+1) + n*log(lmax) - n*log(n)) * Hmatrix(k,k));
Results(3,1)=KSz;
Results(3,2)=pvalue;
 
% KOLMOGOROV-SMIRNOV TEST - LILLIEFORS MODIFICATION
 
% P = [n D20 D15]
P=[5 0.289 0.303;
   6 0.269 0.281;
   7 0.252 0.264;
   8 0.239 0.250;
   9 0.227 0.238;
   10 0.217 0.228;
   11 0.208 0.218;
   12 0.200 0.210;
   13 0.193 0.202;
   14 0.187 0.196;
   15 0.181 0.190;
   16 0.176 0.184;
   17 0.171 0.179;
   18 0.167 0.175;
   19 0.163 0.170;
   20 0.159 0.166;
   25 0.143 0.150;
   30 0.131 0.138;
   40 0.115 0.120;
   100 0.074 0.077;
   400 0.037 0.039;
   900 0.025 0.026];
 
aaa=P(:,1)';
subind=max(find(aaa<n));
upind=subind+1;
xxx=P(subind:upind,:);
 
if aaa(upind)==n
   D20=xxx(2,2);
   D15=xxx(2,3);
else
    D20=xxx(1,2)+(n-aaa(subind))*((xxx(2,2)-xxx(1,2))/(xxx(2,1)-xxx(1,1)));
    D15=xxx(1,3)+(n-aaa(subind))*((xxx(2,3)-xxx(1,3))/(xxx(2,1)-xxx(1,1)));
end
 
a1=-7.01256*(n+2.78019);
b1=2.99587*sqrt(n+2.78019);
c1=2.1804661+0.974598/sqrt(n)+1.67997/n;
 
a2=-7.90289126054*(n^0.98);
b2=3.180370175721*(n^0.49);
c2=2.2947256;
 
if n>100
   D10=(-b2-sqrt(b2^2-4*a2*c2))/(2*a2);
   a=a2;
   b=b2;
   c=c2;
else
   D10=(-b1-sqrt(b1^2-4*a1*c1))/(2*a1);
   a=a1;
   b=b1;
   c=c1;
end
 
if Dn==D10
        pvalue=0.10;
    elseif Dn>D10
        pvalue=exp(a*Dn^2+b*Dn+c-2.3025851);
    elseif Dn>=D15
        pvalue=((0.10-0.15)/(D10-D15))*(Dn-D15)+0.15;
    elseif Dn>=D20
       pvalue=((0.15-0.20)/(D15-D20))*(Dn-D20)+0.20;
    else
       pvalue=0.20;
end
Results(4,1)=Dn;
Results(4,2)=pvalue;
 
% ANDERSON-DARLING TEST
 
adj=1+0.75/n+2.25/(n^2);
i=1:n;
ui=normcdf(zscore(y),0,1);
oneminusui=sort(1-ui);
lastt=(2*i-1).*(log(ui)+log(oneminusui));
asquare=-n-(1/n)*sum(lastt);
AD=asquare*adj;
 
if AD<=0.2
    pvalue=1-exp(-13.436+101.14*AD-223.73*AD^2);
elseif AD<=0.34
    pvalue=1-exp(-8.318+42.796*AD-59.938*AD^2);
elseif AD<=0.6
    pvalue=exp(0.9177-4.279*AD-1.38*AD^2);
elseif AD<=153.467
    pvalue=exp(1.2937*AD-5.709*AD+0.0186*AD^2);
else
    pvalue=0;
end
Results(5,1)=AD;
Results(5,2)=pvalue;
 
% CRAMER - VON MISES TEST
 
adj=1+0.5/n;
i=1:n;
fx=normcdf(zscore(y),0,1);
gx=(fx-((2*i-1)/(2*n))).^2;
CvMteststat=(1/(12*n))+sum(gx);
AdjCvM=CvMteststat*adj;
 
if AdjCvM<0.0275
    pvalue=1-exp(-13.953+775.5*AdjCvM-12542.61*(AdjCvM^2));
elseif AdjCvM<0.051
    pvalue=1-exp(-5.903+179.546*AdjCvM-1515.29*(AdjCvM^2));
elseif AdjCvM<0.092
    pvalue=exp(0.886-31.62*AdjCvM+10.897*(AdjCvM^2));
elseif AdjCvM>=0.093
    pvalue=exp(1.111-34.242*AdjCvM+12.832*(AdjCvM^2));
end
Results(6,1)=AdjCvM;
Results(6,2)=pvalue;
    
% SHAPIRO-WILK TEST
 
a=[];
i=1:n;
mi=norminv((i-0.375)/(n+0.25));
u=1/sqrt(n);
m=mi.^2;
 
a(n)=-2.706056*(u^5)+4.434685*(u^4)-2.07119*(u^3)-0.147981*(u^2)+0.221157*u+mi(n)/sqrt(sum(m));
a(n-1)=-3.58263*(u^5)+5.682633*(u^4)-1.752461*(u^3)-0.293762*(u^2)+0.042981*u+mi(n-1)/sqrt(sum(m));
a(1)=-a(n);
a(2)=-a(n-1);
eps=(sum(m)-2*(mi(n)^2)-2*(mi(n-1)^2))/(1-2*(a(n)^2)-2*(a(n-1)^2));
a(3:n-2)=mi(3:n-2)./sqrt(eps);
    ax=a.*y;
    KT=sum((x-mean(x)).^2);
    b=sum(ax)^2;
    SWtest=b/KT;
mu=0.0038915*(log(n)^3)-0.083751*(log(n)^2)-0.31082*log(n)-1.5861;
sigma=exp(0.0030302*(log(n)^2)-0.082676*log(n)-0.4803);
z=(log(1-SWtest)-mu)/sigma;
pvalue=1-normcdf(z,0,1);
Results(7,1)=SWtest;
Results(7,2)=pvalue;
 
% SHAPIRO-FRANCIA TEST
 
mi=norminv((i-0.375)/(n+0.25));
micarp=sqrt(mi*mi');
weig=mi./micarp;
pay=sum(y.*weig)^2;
payda=sum((y-mean(y)).^2);
SFteststa=pay/payda;
 
u1=log(log(n))-log(n);
u2=log(log(n))+2/log(n);
mu=-1.2725+1.0521*u1;
sigma=1.0308-0.26758*u2;
 
zet=(log(1-SFteststa)-mu)/sigma;
pvalue=1-normcdf(zet,0,1);
Results(8,1)=SFteststa;
Results(8,2)=pvalue;
 
% JARQUE-BERA TEST
 
E=skewness(y);
B=kurtosis(y);
JBtest=n*((E^2)/6+((B-3)^2)/24);
pvalue=1-chi2cdf(JBtest,2);
Results(9,1)=JBtest;
Results(9,2)=pvalue;
 
% D'AGOSTINO - PEARSON TEST
 
beta2=(3*(n^2+27*n-70)*(n+1)*(n+3))/((n-2)*(n+5)*(n+7)*(n+9));
wsquare=-1+sqrt(2*(beta2-1));
delta=1/sqrt(log(sqrt(wsquare)));
alfa=sqrt(2/(wsquare-1));
 
expectedb2=(3*(n-1))/(n+1);
varb2=(24*n*(n-2)*(n-3))/(((n+1)^2)*(n+3)*(n+5));
sqrtbeta=((6*(n^2-5*n+2))/((n+7)*(n+9)))*sqrt((6*(n+3)*(n+5))/(n*(n-2)*(n-3)));
A=6+(8/sqrtbeta)*(2/sqrtbeta+sqrt(1+4/(sqrtbeta^2)));
 
squarerootb=skewness(y);
Y=squarerootb*sqrt(((n+1)*(n+3))/(6*(n-2)));
zsqrtbtest=delta*log(Y/alfa+sqrt((Y/alfa)^2+1));
 
b2=kurtosis(y);
zet=(b2-expectedb2)/sqrt(varb2);
ztestb2=((1-2/(9*A))-((1-2/A)/(1+zet*sqrt(2/(A-4))))^(1/3))/sqrt(2/(9*A));
 
DAPtest=zsqrtbtest^2+ztestb2^2;
 
pvalue=1-chi2cdf(DAPtest,2);
Results(10,1)=DAPtest;
Results(10,2)=pvalue;
 
% Compare p-value to alpha
for i=1:10
    if Results(i,2)>alpha
        Results(i,3)=1;
    else
        Results(i,3)=0;
    end
end
 
% Output display
 
disp(' ') 
disp('Test Name                  Test Statistic   p-value   Normality (1:Normal,0:Not Normal)')
disp('-----------------------    --------------  ---------  --------------------------------')
fprintf('KS Limiting Form               %6.4f \t     %6.4f                 %1.0f \r',KSz,Results(1,2),Results(1,3))
fprintf('KS Stephens Modification       %6.4f \t     %6.4f                 %1.0f \r',dKSz,Results(2,2),Results(2,3))
fprintf('KS Marsaglia Method            %6.4f \t     %6.4f                 %1.0f \r',KSz,Results(3,2),Results(3,3))
fprintf('KS Lilliefors Modification     %6.4f \t     %6.4f                 %1.0f \r',Dn,Results(4,2),Results(4,3))
fprintf('Anderson-Darling Test          %6.4f \t     %6.4f                 %1.0f \r',AD,Results(5,2),Results(5,3))
fprintf('Cramer- Von Mises Test         %6.4f \t     %6.4f                 %1.0f \r',AdjCvM,Results(6,2),Results(6,3))    
fprintf('Shapiro-Wilk Test              %6.4f \t     %6.4f                 %1.0f \r',SWtest,Results(7,2),Results(7,3))
fprintf('Shapiro-Francia Test           %6.4f \t     %6.4f                 %1.0f \r',SFteststa,Results(8,2),Results(8,3))
fprintf('Jarque-Bera Test               %6.4f \t     %6.4f                 %1.0f \r',JBtest,Results(9,2),Results(9,3))
fprintf('DAgostino & Pearson Test       %6.4f \t     %6.4f                 %1.0f \r',DAPtest,Results(10,2),Results(10,3))
 
end


function hAxes = dscatter(X,Y, varargin)
% DSCATTER creates a scatter plot coloured by density.
%
%   DSCATTER(X,Y) creates a scatterplot of X and Y at the locations
%   specified by the vectors X and Y (which must be the same size), colored
%   by the density of the points.
%
%   DSCATTER(...,'MARKER',M) allows you to set the marker for the
%   scatter plot. Default is 's', square.
%
%   DSCATTER(...,'MSIZE',MS) allows you to set the marker size for the
%   scatter plot. Default is 10.
%
%   DSCATTER(...,'FILLED',false) sets the markers in the scatter plot to be
%   outline. The default is to use filled markers.
%
%   DSCATTER(...,'PLOTTYPE',TYPE) allows you to create other ways of
%   plotting the scatter data. Options are "surf','mesh' and 'contour'.
%   These create surf, mesh and contour plots colored by density of the
%   scatter data.
%
%   DSCATTER(...,'BINS',[NX,NY]) allows you to set the number of bins used
%   for the 2D histogram used to estimate the density. The default is to
%   use the number of unique values in X and Y up to a maximum of 200.
%
%   DSCATTER(...,'SMOOTHING',LAMBDA) allows you to set the smoothing factor
%   used by the density estimator. The default value is 20 which roughly
%   means that the smoothing is over 20 bins around a given point.
%
%   DSCATTER(...,'LOGY',true) uses a log scale for the yaxis.
%
%   Examples:
%
%       [data, params] = fcsread('SampleFACS');
%       dscatter(data(:,1),10.^(data(:,2)/256),'log',1)
%       % Add contours
%       hold on
%       dscatter(data(:,1),10.^(data(:,2)/256),'log',1,'plottype','contour')
%       hold off
%       xlabel(params(1).LongName); ylabel(params(2).LongName);
%       
%   See also FCSREAD, SCATTER.
% Copyright 2003-2004 The MathWorks, Inc.
% $Revision:  $   $Date:  $
% Reference:
% Paul H. C. Eilers and Jelle J. Goeman
% Enhancing scatterplots with smoothed densities
% Bioinformatics, Mar 2004; 20: 623 - 628.
lambda = [];
nbins = [];
plottype = 'scatter';
contourFlag = false;
msize = 10;
marker = 's';
logy = false;
filled = true;
if nargin > 2
    if rem(nargin,2) == 1
        error('Bioinfo:IncorrectNumberOfArguments',...
            'Incorrect number of arguments to %s.',mfilename);
    end
    okargs = {'smoothing','bins','plottype','logy','marker','msize','filled'};
    for j=1:2:nargin-2
        pname = varargin{j};
        pval = varargin{j+1};
        k = strmatch(lower(pname), okargs); %#ok
        if isempty(k)
            error('Bioinfo:UnknownParameterName',...
                'Unknown parameter name: %s.',pname);
        elseif length(k)>1
            error('Bioinfo:AmbiguousParameterName',...
                'Ambiguous parameter name: %s.',pname);
        else
            switch(k)
                case 1  % smoothing factor
                    if isnumeric(pval)
                        lambda = pval;
                    else
                        error('Bioinfo:InvalidScoringMatrix','Invalid smoothing parameter.');
                    end
                case 2
                    if isscalar(pval)
                        nbins = [ pval pval];
                    else
                        nbins = pval;
                    end
                case 3
                    plottype = pval;
                case 4
                    logy = pval;
                    Y = log10(Y);
                case 5
                    contourFlag = pval;
                case 6
                    marker = pval;
                case 7
                    msize = pval;
                case 8
                    filled = pval;
            end
        end
    end
end
minx = min(X,[],1);
maxx = max(X,[],1);
miny = min(Y,[],1);
maxy = max(Y,[],1);
if isempty(nbins)
    nbins = [min(numel(unique(X)),200) ,min(numel(unique(Y)),200) ];
end
if isempty(lambda)
    lambda = 20;
end
edges1 = linspace(minx, maxx, nbins(1)+1);
ctrs1 = edges1(1:end-1) + .5*diff(edges1);
edges1 = [-Inf edges1(2:end-1) Inf];
edges2 = linspace(miny, maxy, nbins(2)+1);
ctrs2 = edges2(1:end-1) + .5*diff(edges2);
edges2 = [-Inf edges2(2:end-1) Inf];
[n,p] = size(X);
bin = zeros(n,2);
% Reverse the columns to put the first column of X along the horizontal
% axis, the second along the vertical.
[dum,bin(:,2)] = histc(X,edges1);
[dum,bin(:,1)] = histc(Y,edges2);
H = accumarray(bin,1,nbins([2 1])) ./ n;
G = smooth1D(H,nbins(2)/lambda);
F = smooth1D(G',nbins(1)/lambda)';
% = filter2D(H,lambda);
if logy
    ctrs2 = 10.^ctrs2;
    Y = 10.^Y;
end
okTypes = {'surf','mesh','contour','image','scatter'};
k = strmatch(lower(plottype), okTypes); %#ok
if isempty(k)
    error('dscatter:UnknownPlotType',...
        'Unknown plot type: %s.',plottype);
elseif length(k)>1
    error('dscatter:AmbiguousPlotType',...
        'Ambiguous plot type: %s.',plottype);
else
    switch(k)
        case 1 %'surf'
            h = surf(ctrs1,ctrs2,F,'edgealpha',0);
        case 2 % 'mesh'
            h = mesh(ctrs1,ctrs2,F);
        case 3 %'contour'
            [dummy, h] =contour(ctrs1,ctrs2,F);
        case 4 %'image'
            nc = 256;
            F = F./max(F(:));
            colormap(repmat(linspace(1,0,nc)',1,3));
            h =image(ctrs1,ctrs2,floor(nc.*F) + 1);
        case 5 %'scatter'
            F = F./max(F(:));
            ind = sub2ind(size(F),bin(:,1),bin(:,2));
            col = F(ind);
            if filled
                h = scatter(X,Y,msize,col,marker,'filled');
            else
                h = scatter(X,Y,msize,col,marker);
            end
    end
end
if logy
    set(gca,'yscale','log');
end
if nargout > 0
    hAxes = get(h,'parent');
end
%%%% This method is quicker for symmetric data.
% function Z = filter2D(Y,bw)
% z = -1:(1/bw):1;
% k = .75 * (1 - z.^2);
% k = k ./ sum(k);
% Z = filter2(k'*k,Y);
function Z = smooth1D(Y,lambda)
[m,n] = size(Y);
E = eye(m);
D1 = diff(E,1);
D2 = diff(D1,1);
P = lambda.^2 .* D2'*D2 + 2.*lambda .* D1'*D1;
Z = (E + P) \ Y;
end
end


function [varargout]=errorbarxy(varargin)
%   ERRORBARXY is a function to generate errorbars on both x and y axes 
%   with specified errors modified from codes written by Nils Sjöberg 
%   (http://www.mathworks.com/matlabcentral/fileexchange/5444-xyerrorbar)
%  
%   errorbarxy(x, y, lerrx, uerrx, lerry, uerry) plots the data with errorbars on both 
%   x and y axes with error bars [x-lerrx, x+uerrx] and [y-lerry, y+uerry]. If there is
%   no error on one axis, set corresponding lower and upper bounds to [].
%
%   errorbarxy(x, y, errx, erry) plots the data with errorbars on both x and
%   y axes with error bars [x-errx, x+errx] and [y-erry, y+erry]. If there 
%   is no error on one axis, set corresponding errors to [].
%   
%   errorbarxy(..., S) plots data as well as errorbars using specified
%   formatting string. S is a cell array of 3 element, {sData, cEBx, cEBy},
%   where sData specifies the format of main plot, cEBx specifies the 
%   color of errorbars along x axis and cEBy specifies the color of 
%   errorbars along y axis. The formatting string for the main plot made 
%   from one element from any or all the following 3 columns, while the 
%   other two strings made only from the first colume (color):
%            b     blue          .     point              -     solid
%            g     green         o     circle             :     dotted
%            r     red           x     x-mark             -.    dashdot 
%            c     cyan          +     plus               --    dashed   
%            m     magenta       *     star             (none)  no line
%            y     yellow        s     square
%            k     black         d     diamond
%            w     white         v     triangle (down)
%                                ^     triangle (up)
%                                <     triangle (left)
%                                >     triangle (right)
%                                p     pentagram
%                                h     hexagram
% 
%   
%   errorbarxy(AX,...) plots into AX instead of GCA.
%   
%   H = errorbar(...) returns a vector of errorbarseries handles in H,
%   within which the first element is the handle to the main data plot and
%   the remaining elements are handles to the rest errorbars.
%   H is organized as follows:
%   H.hMain is the handle of the main plot
%   H.hErrorbar is a Nx6 matrix containing handles for all error bar lines,
%               where N is the number of samples. For each sample, 6
%               errorbar handles are saved in such an order:
%               [Horizontal bar, H bar left cap, H bar right cap, 
%                Vertical bar, V bar lower cap, V bar upper cap]
%
%   For example
%       x = 1:10;
%       xe = 0.5*ones(size(x));
%       y = sin(x);
%       ye = std(y)*ones(size(x));
%       H=errorbarxy(x,y,xe,ye,{'ko-', 'b', 'r'});
%    draws symmetric error bars on both x and y axes.
%
%   NOTE: errorbars are excluded from legend display. If you need to
%   include errorbars in legend display, do the followings:
%       H=errorbarxy(...);
%       arrayfun(@(d) set(get(get(d,'Annotation'),'LegendInformation'),...
%       'IconDisplayStyle','on'), H(2:end)); % include errorbars
%       hEB=hggroup;
%       set(H(2:end),'Parent',hEB);
%       set(get(get(hEB,'Annotation'),'LegendInformation'),...
%       'IconDisplayStyle','on'); % include errorbars in legend as a group.
%       legend('Main plot', 'Error bars');
%
%   Developed under Matlab version 7.10.0.499 (R2010a)
%   Created by Qi An
%   anqi2000@gmail.com
%   QA 2/7/2013 initial skeleton
%   QA 2/12/2013    Added support to plot on specified axes; Added support
%                   to specify color of plots and errorbars; Output a
%                   vector of errbar series handles; Fixed a couple of 
%                   minor bugs. 
%   QA 2/13/2013    Excluded errorbars from legend display.
%   QA 8/19/2013    Fixed a bug in errorbar cap display.
%   QA 9/24/2013    Fixed a bug in figure handle output.
%   QA 1/16/2014    Reorganize the output handle structure.
%   QA 2/4/2014     Allow customization on main plot using formatting
%                   string. 
%   QA 4/28/2014    Check for formatting string. Fixed a bug when
%                   specifying axis to plot. 
%   QA 11/23/2015   Fixed a bug when some of
%                   errx/erry/lerrx/uerrx/lerry/uerry are not specified the
%                   code will error out. 
%   QA 11/23/2015   The code will "remember" if the axis is set to be "HOLD ON".
%% handle inputs
if ishandle(varargin{1}) % first argument is a handle
    if strcmpi(get(varargin{1}, 'type'), 'axes') % the handle is for an axes
        axes(varargin{1}); % set the handle to be current
    
        varargin(1)=[];
    end
end
if length(varargin)<4
    error('Insufficient number of inputs');
    return;
end
%% assign values
x=varargin{1};
y=varargin{2};
if length(x)~=length(y)
    error('x and y must have the same number of elements!')
    return
end
if iscell(varargin{end}) & length(varargin{end})==3 % search for formatting strings
    color=varargin{end};
    varargin(end)=[]; % remove formatting string from optional input structure
else
    color={'b', 'r', 'r'};
end
if length(varargin)==4 % using errorbarxy(x, y, errx, erry)
    errx=varargin{3};
    erry=varargin{4};
    if ~isempty(errx)
        lx=x-errx;
        ux=x+errx;
    else
        lx=[];
        ux=[];
    end
    if ~isempty(erry)
        ly=y-erry;
        uy=y+erry;
    else
        ly=[];
        uy=[];
    end
    
elseif length(varargin)==6 % using errorbarxy(x, y, lerrx, uerrx, lerry, uerry)
    lx=x-varargin{3};
    ux=x+varargin{4};
    ly=y-varargin{5};
    uy=y+varargin{6};
    if ~isempty(lx)
        errx=(ux-lx)/2;
    else
        errx=[];
    end
    if ~isempty(ly)
        erry=(uy-ly)/2;
    else
        erry=[];
    end
    
else
    error('Wrong number of inputs!');
end
%% plot data and errorbars
flagHold=ishold; % record the current status of "HOLD"
h=plot(x,y, color{1}); % main plot
allh=nan(length(x), 6); % all errorbar handles
for k=1:length(x)
    if ~isempty(lx) & ~isempty(ly) % both errors are specified
        l1=line([lx(k) ux(k)],[y(k) y(k)]);
        hold on;
        l2=line([lx(k) lx(k)],[y(k)-0.1*erry(k) y(k)+0.1*erry(k)]);
        l3=line([ux(k) ux(k)],[y(k)-0.1*erry(k) y(k)+0.1*erry(k)]);
        l4=line([x(k) x(k)],[ly(k) uy(k)]);
        l5=line([x(k)-0.1*errx(k) x(k)+0.1*errx(k)],[ly(k) ly(k)]);
        l6=line([x(k)-0.1*errx(k) x(k)+0.1*errx(k)],[uy(k) uy(k)]);
        allh(k, :)=[l1, l2, l3, l4, l5, l6];
    elseif isempty(lx) & ~isempty(ly) % x errors are not specified
        l4=line([x(k) x(k)],[ly(k) uy(k)]);
        hold on;
        errx=nanmean(abs(diff(x)));
        l5=line([x(k)-0.1*errx x(k)+0.1*errx],[ly(k) ly(k)]);
        l6=line([x(k)-0.1*errx x(k)+0.1*errx],[uy(k) uy(k)]);
        allh(k, 4:6)=[l4, l5, l6];
    elseif ~isempty(lx) & isempty(ly) % y errors are not specified
        l1=line([lx(k) ux(k)],[y(k) y(k)]);
        hold on;
        erry=nanmean(abs(diff(y)));
        l2=line([lx(k) lx(k)],[y(k)-0.1*erry y(k)+0.1*erry]);
        l3=line([ux(k) ux(k)],[y(k)-0.1*erry y(k)+0.1*erry]);
        allh(k, 1:3)=[l1, l2, l3];
    else % both errors are not specified
    end
    if exist('l1', 'var')
        h1=[l1, l2, l3]; % all handles
        set(h1, 'color', color{2});
    end
    if exist('l4', 'var')
        h1=[l4, l5, l6]; % all handles
        set(h1, 'color', color{3});
    end
end
arrayfun(@(d) set(get(get(d,'Annotation'),'LegendInformation'), 'IconDisplayStyle','off'), allh(~isnan(allh))); % exclude errorbars from legend
out.hMain=h;
out.hErrorbar=allh;
hold off;
if flagHold % set the axis to the original status, e.g hold on or off
    hold on;
end
%% handle outputs
if nargout>0
    varargout{1}=out;
end

end

%Median polish fails when more than half of row/columns are hits
function [x, grand_effect, row_effect, column_effect, resid] = median_polish(x, tol, maxiter)
% MEDIAN_POLISH Fits an additive model using Tukey's median polish procedure. 
%   MEDIAN_POLISH(X) fits an additive model to a 2D input matrix, X, assuming a 
%   decomposition of (constant + rows + columns).
%
%   Median polishing is useful for removing spatial trends in the data by 
%   alternately removing medians from the rows and columns of the data. The 
%   algorithm proceeds as follows. Considering the rows first, for each row the 
%   row median is subtracted from every element in that row. Then, for each 
%   column, the median of the revised numbers is then subtracted from every 
%   element in that column. This process is repeated until all convergence, or 
%   a maximum number of iterations.
%
%   In this implementation, NaNs are assumed to be missing data.
%
%   Syntax:
%
%   p = median_polish(X);
%   p = median_polish(X, tol);
%   p = median_polish(X, tol, maxiter);
%   [p, ge] = median_polish(...);
%   [p, ge, re] = median_polish(...);
%   [p, ge, re, ce] = median_polish(...);
%   [p, ge, re, ce, resid] = median_polish(...);
%   
%   X       : A 2D input matrix
%   tol     : Tolerance threshold for stopping iterations
%   maxiter : The maximum number of iterations
%
%   p       : The median polished matrix.
%   ge      : The fitted constant term (also known as the Grand Effect).
%   re      : The fitted row effect.
%   ce      : The fitted column effect.
%   resid   : Residuals
%
%   Example: If X = [13 17 26 18 29;
%                    42 48 57 41 59;
%                    34 31 36 22 41];
%
%   then median_polish(X) returns [ 0 -1  0  7  0;
%                                  -1  0  1  0  0;
%                                   9  1 -2 -1  0]
%
%   Class support for input X:
%      float: double, single
%
%   Reference: Tukey, John W. Exploratory Data Analysis, Addison-Wesley 1977 
%              ISBN 0-201-07616-0

Narg = nargin;
if (Narg < 2)
    tol = 0.001;
end
if (Narg < 3)
    maxiter = 1000;
end

S = size(x);
N_dim = length(S);

% Parameter Check
if (N_dim ~= 2)
    error('Require a 2 dimensional matrix as input');
end
if (tol <= 0)
    error('Convergence Tolerance (tol) must be positive');
end
if (maxiter < 1)
    error('Maximum number of iterations must greater or equal to 1');
end

xorig = x;
grand_effect = NaN;
row_effect = zeros(1, S(2));
column_effect = zeros(S(1), 1);

for it=1:maxiter    
    
    % Row Sweep
    rm = nanmedian(x, 1); %find the row medians for each row
    x = bsxfun(@minus, x, rm); %subtract each element in a row by its row median

    row_effect = (row_effect + rm);
    rmm = nanmedian(row_effect); %find median of the row medians i.e. overall effect 

%     functional_raw_effect=row_effect-rmm; 
    
    % Column Sweep
    cm = nanmedian(x, 2);
    x = bsxfun(@minus, x, cm);
    
    column_effect = column_effect + cm;
    cmm = nanmedian(column_effect);

    % Grand Effect
    ge_prime = grand_effect;
    grand_effect = rmm + cmm;
    
%     functional_column_effect-grand_effect;
    
    d = abs(ge_prime - grand_effect);
    if (d < tol)
        break;
    end
end

resid = xorig - x;  % resid is the polished matrix, x is the residual 
end

function [x, grand_effect, row_effect, column_effect, resid] = corrected_median_polish(x, tol, maxiter)
%   Reference: https://www.jstor.org/stable/pdf/41724578.pdf?refreqid=excelsior%3A047884ababfa693489988ea5819bfb4d

Narg = nargin;
if (Narg < 2)
    tol = 0.001;
end
if (Narg < 3)
    maxiter = 10000;
end

S = size(x);
N_dim = length(S);

% Parameter Check
if (N_dim ~= 2)
    error('Require a 2 dimensional matrix as input');
end
if (tol <= 0)
    error('Convergence Tolerance (tol) must be positive');
end
if (maxiter < 1)
    error('Maximum number of iterations must greater or equal to 1');
end

xorig = x;
row_effect = zeros(1, S(2));
column_effect = zeros(S(1), 1);
functional_grand_effect=0;
functional_row_effect=0;
functional_column_effect=0;
rm_previous=0;

for it=1:maxiter    
    
    % Row Sweep
    rm = nanmedian(x, 1); %find the row medians for each row    
    x = bsxfun(@minus, x, rm); %subtract each element in a particular row by its row median
 
    functional_grand_effect=functional_grand_effect+nanmedian(rm);  
    functional_row_effect=rm-functional_grand_effect+functional_row_effect; 
    
    if prod(IsNear(rm,rm_previous))
        break;
    end
    
    % Column Sweep
    cm = nanmedian(x, 2);
    x = bsxfun(@minus, x, cm);
    
    functional_grand_effect=functional_grand_effect+nanmedian(cm);  
    functional_column_effect=cm-functional_grand_effect+functional_column_effect;

    rm_previous=rm; %stores row median vector from this iteration
end

grand_effect=functional_grand_effect;
resid = xorig - x;  % Calculate Residuals
%The internal variable "resid" isn't really the residuals, but the fitted matrix
end

function tf=IsNear(a,b,tol)
%ISNEAR True Where Nearly Equal.
% ISNEAR(A,B) returns a logical array the same size as A and B that is True
% where A and B are almost equal to each other and False where they are not.
% A and B must be the same size or one can be a scalar.
% ISNEAR(A,B,TOL) uses the tolerance TOL to determine nearness. In this
% case, TOL can be a scalar or an array the same size as A and B.
%
% When TOL is not provided, TOL = SQRT(eps).
%
% Use this function instead of A==B when A and B contain noninteger values.
% D.C. Hanselman, University of Maine, Orono, ME 04469
% Mastering MATLAB 7
% 2005-03-09
%--------------------------------------------------------------------------
if nargin==2
%    tol=sqrt(eps);       % original version
	tol=sqrt(eps(max(abs(a),abs(b))));     %  my version. sqrt seems like 'overdamping'
end
% when in need of optimization, drop the error checks
if ~isnumeric(a) || isempty(a) || ~isnumeric(b) || isempty(b) ||...
   ~isnumeric(tol) || isempty(tol)
   error('Inputs Must be Numeric.')
end
if any(size(a)~=size(b)) && numel(a)>1 && numel(b)>1
   error('A and B Must be the Same Size or Either can be a Scalar.')
end
% main line
tf=abs((a-b))<=abs(tol);
end

function [smoothed] = fLOESS(noisy,span) 
%
% Author; Gabriel Marsh
% Latest revision; 
% 22/02/2016    Included non-uniformly spaced x-data capability
%
%% DESCRIPTION
% Function fLOESS performs LOESS (locally weighted regression fitting using 
% a 2nd order polynomial) to one dimensional data. This might be considered 
% a better approach to LOWESS, which produces a locally weighted regression 
% using a linear fit.
% 
%% INPUTS
% noisy     =   An (nx1) vector containing the noisy data to be smoothed,
%               or, and(nx2) array containing x-data in the first column
%               (increasing values) and noisy y-data in the second column.
% span      =   A value specifying the fraction of data to use with the 
%               fitting procedure. Minimum value is span = 4/n
%
%% OUTPUTS
% smoothed  =   An (nx1) vector of smoothed data points
%
%% EXAMPLE
% generate some random data
% x = 10*sort(rand(100,1));
% clean = cos(1.0*x + 1) + 1.0;
% noisy =  [x,clean + 1.5*(rand(length(x),1)-0.5)];
% 
% % define the span length (randomised between 10 and length of data)
% span = 0.1 + 0.9*rand(1,1);
% 
% % fit the data
% smoothed = fLOESS(noisy,span); 
% 
% % Plot the data
% hold off
% plot(x,clean,'k')
% hold all
% plot(x,noisy(:,2),'.')
% plot(x,smoothed,'LineWidth',2)
% legend({'clean','noisy',['smoothed (span = ',sprintf('%1.2f',span),')']})

%% Error checking
% Check suffient number of data points will be included in the fitting
if length(noisy)*span<4 
    error('myApp:argChk','input arg "span" is too low')    
end
% Default x-data
if size(noisy,2)<2
    noisy = [(1:1:length(noisy))',noisy];
end
%% Smooth the data points
% define variables
x = noisy(:,1);
y = noisy(:,2);
n = length(noisy);
r = x(end) - x(1);
hlims = [span,x(1);...
    (span)/2,x(1)+r*span/2;...
    (span)/2,x(1)+r*(1-span/2);...
    span,x(end)];  
% Find the LOESS fit to the data
smoothed = zeros(n,1); % pre-allocate space
for i = 1:n
    
    % define the tricube weight function
    h = interp1(hlims(:,2),hlims(:,1),x(i));
    w = (1-abs((x./max(x)-x(i)./max(x))/h).^3).^3;
    
    % data points outwith the defined span can be ignored (for speed)
    w_idx = w>0;
    w_ = w(w_idx);
    x_ = x(w_idx);
    y_ = y(w_idx);
    
    % Calculate the weighted coefficients
    XX =   [nansum(w_.*x_.^0), nansum(w_.*x_.^1), nansum(w_.*x_.^2);...
            nansum(w_.*x_.^1), nansum(w_.*x_.^2), nansum(w_.*x_.^3);...
            nansum(w_.*x_.^2), nansum(w_.*x_.^3), nansum(w_.*x_.^4)];
    
    YY =   [nansum(w_.*y_.*(x_.^0));...
            nansum(w_.*y_.*(x_.^1));...
            nansum(w_.*y_.*(x_.^2))];
    
    CC = XX\YY;
    
    % calculate the fitted data point
    smoothed(i) = CC(1) + CC(2)*x(i) + CC(3)*x(i).^2;
    
end
end

function map = turbo(m)
%TURBO   Turbo colormap.
%   TURBO(M) returns an M-by-3 matrix containing the turbo colormap, a
%   variant of the jet colormap that is more perceptually uniform.
%
%   See also JET, COLORMAP.
if nargin < 1
   f = get(groot,'CurrentFigure');
   if isempty(f)
      m = size(get(groot,'DefaultFigureColormap'),1);
   else
      m = size(f.Colormap,1);
   end
end
values = [
     0.18995, 0.07176, 0.23217;
     0.19483, 0.08339, 0.26149;
     0.19956, 0.09498, 0.29024;
     0.20415, 0.10652, 0.31844;
     0.20860, 0.11802, 0.34607;
     0.21291, 0.12947, 0.37314;
     0.21708, 0.14087, 0.39964;
     0.22111, 0.15223, 0.42558;
     0.22500, 0.16354, 0.45096;
     0.22875, 0.17481, 0.47578;
     0.23236, 0.18603, 0.50004;
     0.23582, 0.19720, 0.52373;
     0.23915, 0.20833, 0.54686;
     0.24234, 0.21941, 0.56942;
     0.24539, 0.23044, 0.59142;
     0.24830, 0.24143, 0.61286;
     0.25107, 0.25237, 0.63374;
     0.25369, 0.26327, 0.65406;
     0.25618, 0.27412, 0.67381;
     0.25853, 0.28492, 0.69300;
     0.26074, 0.29568, 0.71162;
     0.26280, 0.30639, 0.72968;
     0.26473, 0.31706, 0.74718;
     0.26652, 0.32768, 0.76412;
     0.26816, 0.33825, 0.78050;
     0.26967, 0.34878, 0.79631;
     0.27103, 0.35926, 0.81156;
     0.27226, 0.36970, 0.82624;
     0.27334, 0.38008, 0.84037;
     0.27429, 0.39043, 0.85393;
     0.27509, 0.40072, 0.86692;
     0.27576, 0.41097, 0.87936;
     0.27628, 0.42118, 0.89123;
     0.27667, 0.43134, 0.90254;
     0.27691, 0.44145, 0.91328;
     0.27701, 0.45152, 0.92347;
     0.27698, 0.46153, 0.93309;
     0.27680, 0.47151, 0.94214;
     0.27648, 0.48144, 0.95064;
     0.27603, 0.49132, 0.95857;
     0.27543, 0.50115, 0.96594;
     0.27469, 0.51094, 0.97275;
     0.27381, 0.52069, 0.97899;
     0.27273, 0.53040, 0.98461;
     0.27106, 0.54015, 0.98930;
     0.26878, 0.54995, 0.99303;
     0.26592, 0.55979, 0.99583;
     0.26252, 0.56967, 0.99773;
     0.25862, 0.57958, 0.99876;
     0.25425, 0.58950, 0.99896;
     0.24946, 0.59943, 0.99835;
     0.24427, 0.60937, 0.99697;
     0.23874, 0.61931, 0.99485;
     0.23288, 0.62923, 0.99202;
     0.22676, 0.63913, 0.98851;
     0.22039, 0.64901, 0.98436;
     0.21382, 0.65886, 0.97959;
     0.20708, 0.66866, 0.97423;
     0.20021, 0.67842, 0.96833;
     0.19326, 0.68812, 0.96190;
     0.18625, 0.69775, 0.95498;
     0.17923, 0.70732, 0.94761;
     0.17223, 0.71680, 0.93981;
     0.16529, 0.72620, 0.93161;
     0.15844, 0.73551, 0.92305;
     0.15173, 0.74472, 0.91416;
     0.14519, 0.75381, 0.90496;
     0.13886, 0.76279, 0.89550;
     0.13278, 0.77165, 0.88580;
     0.12698, 0.78037, 0.87590;
     0.12151, 0.78896, 0.86581;
     0.11639, 0.79740, 0.85559;
     0.11167, 0.80569, 0.84525;
     0.10738, 0.81381, 0.83484;
     0.10357, 0.82177, 0.82437;
     0.10026, 0.82955, 0.81389;
     0.09750, 0.83714, 0.80342;
     0.09532, 0.84455, 0.79299;
     0.09377, 0.85175, 0.78264;
     0.09287, 0.85875, 0.77240;
     0.09267, 0.86554, 0.76230;
     0.09320, 0.87211, 0.75237;
     0.09451, 0.87844, 0.74265;
     0.09662, 0.88454, 0.73316;
     0.09958, 0.89040, 0.72393;
     0.10342, 0.89600, 0.71500;
     0.10815, 0.90142, 0.70599;
     0.11374, 0.90673, 0.69651;
     0.12014, 0.91193, 0.68660;
     0.12733, 0.91701, 0.67627;
     0.13526, 0.92197, 0.66556;
     0.14391, 0.92680, 0.65448;
     0.15323, 0.93151, 0.64308;
     0.16319, 0.93609, 0.63137;
     0.17377, 0.94053, 0.61938;
     0.18491, 0.94484, 0.60713;
     0.19659, 0.94901, 0.59466;
     0.20877, 0.95304, 0.58199;
     0.22142, 0.95692, 0.56914;
     0.23449, 0.96065, 0.55614;
     0.24797, 0.96423, 0.54303;
     0.26180, 0.96765, 0.52981;
     0.27597, 0.97092, 0.51653;
     0.29042, 0.97403, 0.50321;
     0.30513, 0.97697, 0.48987;
     0.32006, 0.97974, 0.47654;
     0.33517, 0.98234, 0.46325;
     0.35043, 0.98477, 0.45002;
     0.36581, 0.98702, 0.43688;
     0.38127, 0.98909, 0.42386;
     0.39678, 0.99098, 0.41098;
     0.41229, 0.99268, 0.39826;
     0.42778, 0.99419, 0.38575;
     0.44321, 0.99551, 0.37345;
     0.45854, 0.99663, 0.36140;
     0.47375, 0.99755, 0.34963;
     0.48879, 0.99828, 0.33816;
     0.50362, 0.99879, 0.32701;
     0.51822, 0.99910, 0.31622;
     0.53255, 0.99919, 0.30581;
     0.54658, 0.99907, 0.29581;
     0.56026, 0.99873, 0.28623;
     0.57357, 0.99817, 0.27712;
     0.58646, 0.99739, 0.26849;
     0.59891, 0.99638, 0.26038;
     0.61088, 0.99514, 0.25280;
     0.62233, 0.99366, 0.24579;
     0.63323, 0.99195, 0.23937;
     0.64362, 0.98999, 0.23356;
     0.65394, 0.98775, 0.22835;
     0.66428, 0.98524, 0.22370;
     0.67462, 0.98246, 0.21960;
     0.68494, 0.97941, 0.21602;
     0.69525, 0.97610, 0.21294;
     0.70553, 0.97255, 0.21032;
     0.71577, 0.96875, 0.20815;
     0.72596, 0.96470, 0.20640;
     0.73610, 0.96043, 0.20504;
     0.74617, 0.95593, 0.20406;
     0.75617, 0.95121, 0.20343;
     0.76608, 0.94627, 0.20311;
     0.77591, 0.94113, 0.20310;
     0.78563, 0.93579, 0.20336;
     0.79524, 0.93025, 0.20386;
     0.80473, 0.92452, 0.20459;
     0.81410, 0.91861, 0.20552;
     0.82333, 0.91253, 0.20663;
     0.83241, 0.90627, 0.20788;
     0.84133, 0.89986, 0.20926;
     0.85010, 0.89328, 0.21074;
     0.85868, 0.88655, 0.21230;
     0.86709, 0.87968, 0.21391;
     0.87530, 0.87267, 0.21555;
     0.88331, 0.86553, 0.21719;
     0.89112, 0.85826, 0.21880;
     0.89870, 0.85087, 0.22038;
     0.90605, 0.84337, 0.22188;
     0.91317, 0.83576, 0.22328;
     0.92004, 0.82806, 0.22456;
     0.92666, 0.82025, 0.22570;
     0.93301, 0.81236, 0.22667;
     0.93909, 0.80439, 0.22744;
     0.94489, 0.79634, 0.22800;
     0.95039, 0.78823, 0.22831;
     0.95560, 0.78005, 0.22836;
     0.96049, 0.77181, 0.22811;
     0.96507, 0.76352, 0.22754;
     0.96931, 0.75519, 0.22663;
     0.97323, 0.74682, 0.22536;
     0.97679, 0.73842, 0.22369;
     0.98000, 0.73000, 0.22161;
     0.98289, 0.72140, 0.21918;
     0.98549, 0.71250, 0.21650;
     0.98781, 0.70330, 0.21358;
     0.98986, 0.69382, 0.21043;
     0.99163, 0.68408, 0.20706;
     0.99314, 0.67408, 0.20348;
     0.99438, 0.66386, 0.19971;
     0.99535, 0.65341, 0.19577;
     0.99607, 0.64277, 0.19165;
     0.99654, 0.63193, 0.18738;
     0.99675, 0.62093, 0.18297;
     0.99672, 0.60977, 0.17842;
     0.99644, 0.59846, 0.17376;
     0.99593, 0.58703, 0.16899;
     0.99517, 0.57549, 0.16412;
     0.99419, 0.56386, 0.15918;
     0.99297, 0.55214, 0.15417;
     0.99153, 0.54036, 0.14910;
     0.98987, 0.52854, 0.14398;
     0.98799, 0.51667, 0.13883;
     0.98590, 0.50479, 0.13367;
     0.98360, 0.49291, 0.12849;
     0.98108, 0.48104, 0.12332;
     0.97837, 0.46920, 0.11817;
     0.97545, 0.45740, 0.11305;
     0.97234, 0.44565, 0.10797;
     0.96904, 0.43399, 0.10294;
     0.96555, 0.42241, 0.09798;
     0.96187, 0.41093, 0.09310;
     0.95801, 0.39958, 0.08831;
     0.95398, 0.38836, 0.08362;
     0.94977, 0.37729, 0.07905;
     0.94538, 0.36638, 0.07461;
     0.94084, 0.35566, 0.07031;
     0.93612, 0.34513, 0.06616;
     0.93125, 0.33482, 0.06218;
     0.92623, 0.32473, 0.05837;
     0.92105, 0.31489, 0.05475;
     0.91572, 0.30530, 0.05134;
     0.91024, 0.29599, 0.04814;
     0.90463, 0.28696, 0.04516;
     0.89888, 0.27824, 0.04243;
     0.89298, 0.26981, 0.03993;
     0.88691, 0.26152, 0.03753;
     0.88066, 0.25334, 0.03521;
     0.87422, 0.24526, 0.03297;
     0.86760, 0.23730, 0.03082;
     0.86079, 0.22945, 0.02875;
     0.85380, 0.22170, 0.02677;
     0.84662, 0.21407, 0.02487;
     0.83926, 0.20654, 0.02305;
     0.83172, 0.19912, 0.02131;
     0.82399, 0.19182, 0.01966;
     0.81608, 0.18462, 0.01809;
     0.80799, 0.17753, 0.01660;
     0.79971, 0.17055, 0.01520;
     0.79125, 0.16368, 0.01387;
     0.78260, 0.15693, 0.01264;
     0.77377, 0.15028, 0.01148;
     0.76476, 0.14374, 0.01041;
     0.75556, 0.13731, 0.00942;
     0.74617, 0.13098, 0.00851;
     0.73661, 0.12477, 0.00769;
     0.72686, 0.11867, 0.00695;
     0.71692, 0.11268, 0.00629;
     0.70680, 0.10680, 0.00571;
     0.69650, 0.10102, 0.00522;
     0.68602, 0.09536, 0.00481;
     0.67535, 0.08980, 0.00449;
     0.66449, 0.08436, 0.00424;
     0.65345, 0.07902, 0.00408;
     0.64223, 0.07380, 0.00401;
     0.63082, 0.06868, 0.00401;
     0.61923, 0.06367, 0.00410;
     0.60746, 0.05878, 0.00427;
     0.59550, 0.05399, 0.00453;
     0.58336, 0.04931, 0.00486;
     0.57103, 0.04474, 0.00529;
     0.55852, 0.04028, 0.00579;
     0.54583, 0.03593, 0.00638;
     0.53295, 0.03169, 0.00705;
     0.51989, 0.02756, 0.00780;
     0.50664, 0.02354, 0.00863;
     0.49321, 0.01963, 0.00955;
     0.47960, 0.01583, 0.01055];
P = size(values,1);
map = interp1(1:P, values, linspace(1,P,m), 'linear');
end

function RunRcode(RscriptFileName,Rpath)
% This function calls R to run R script (.r file) under Matlab, and returns 'runR.log' in the same folder with the input R script file.
% This code only works in Windows environments. It might work in Mac by modifying 'FindRpath'. 
% 'RscriptFileName' : path + filename of the R script to be run.
% 'Rpath' (optional) : the path for the installed 'R.exe'.  e.g.  Rpath = 'C:\Program Files\R\R-3.1.1\bin';
% If 'Rpath' is not provided, 'FindRpath' will be executed to automatically find the path for R in Windows Program Files folder.
% Example: 
% >> Rpath = 'C:\Program Files\R\R-3.1.1\bin';
% >> RscriptFileName = 'D:\test\lmm.R';
% >> RunRcode(RscriptFileName, Rpath);
% Update:
% Ver. 1.4  Dec-14-2017  support parallel computing (run several R codes simultaneously)
% Weirong Chen   March-8-2015
if nargin<2 || isempty(Rpath), Rpath=FindRpath;end
sep=filesep;
[p,f,~]=fileparts(RscriptFileName);
if isempty(p), p = pwd;end
logFName=[p sep f '.R.log'];
commandline=['"' Rpath sep 'R.exe" CMD BATCH "' RscriptFileName '" "' logFName '"'];
system(commandline);
end %RunRcode
%% Required subfunctions: 
function Rpath=FindRpath
% This function finds the path for the installed R (Project for Statistical Computing) in Windows environment.
% Only works in Windows environments.
% e.g.:
% Rpath=FindPathR
% >> 'C:\Program Files\R\R-3.1.1\bin'
sep = filesep; env=myGetEnv; 
a=FindWhich(env(:,1),'ProgramFiles');
b=FindWhich(env(:,1),'ProgramW6432'); 
c=FindWhich(env(:,1),'ProgramFiles(x86)');
n=[a;b;c]; isfound=0;
 for i=1:length(n)
     programPath=env{n(i),2};
     D=dir([programPath filesep 'R']);
     if ~isempty(D)
         A={D.name}; B=find(cell2mat(cellfun(@(s) ~isempty(strfind(s,'R-')),A,'uniformoutput',0)),1);
         if ~isempty(B),  isfound=1;Rpath=[programPath sep 'R' sep A{B} sep 'bin'];break; end
     end%
 end
if isfound==0,  Rpath=[];end
end % end of FindRpath
function env=myGetEnv
% Get the environmental values from the operation system.
% Returns key-value pairs stored in 'env' cell array.
% e.g.:
%  >> env=myGetEnv;
% >>  env{8,1} =  'ProgramFiles'
%  >> env{8,2} =  'C:\Program Files'
% Weirong Chen  March-8-2015
envmap = java.lang.System.getenv();
envkey=cell(envmap.keySet.toArray);
envvalue=cell(envmap.values.toArray);
env=[envkey envvalue];
end % end of function
function n=FindWhich(StringCellArray, TargetString, nOutput)
% This funcion finds the 'TargetString' in a string cell array and returns
% the serial number of the element found in 'StringCellArray'.
% 'nOutput' = number of output elements.
% Weirong Chen    SEP-14-2013
sn=1:length(StringCellArray); A=cellismember(StringCellArray,TargetString); n=sn(A);
if nargin<3, return;end
if numel(n)>0, n=n(1:nOutput);end
end % FindWhich
function Lia=cellismember(A,B) 
% The built-in "ismember" function in MATLAB fails to perform when the input variables are cells containing different types of variables.
% This function 'cellismember' is a function that performs 'ismember' on
%  cells with various data types.
%  The input A and B must be cell arrays.
%  Example: 
%  Input: A = {'ab','cd', NaN, [], 5, 1}; B = {[], 'cd', NaN, 1};
%  output: Lia = [0 1 1 1 0 1]; 
%
% Acknowledgement: 
% This function greatly benefits from Jan Simon's comments. The previous version was errorful. 
% See 'ismember' for more information
% Weirong Chen   Apr-16-2
% Update: Jun-1-2015015
if ~iscell(B) && ischar(B), B={B}; end% Convert single value into 1x1 cell array of string
str_Index_A = cellfun('isclass', A, 'char');
str_Index_B = cellfun('isclass', B, 'char');
NaN_Index_A=logical(cell2mat(cellfun(@sum, cellfun(@isnan, A,'UniformOutput',false),'UniformOutput',false)));
NaN_Index_B=logical(cell2mat(cellfun(@sum, cellfun(@isnan, B,'UniformOutput',false),'UniformOutput',false)));
empty_Index_A=cellfun(@isempty, A);
empty_Index_B=cellfun(@isempty, B);
num_Index_A=cellfun(@isnumeric, A) & ~NaN_Index_A & ~empty_Index_A; % 'isnumeric' includes NaN and EMPTY.
num_Index_B=cellfun(@isnumeric, B) & ~NaN_Index_B & ~empty_Index_B; % 'isnumeric' includes NaN and EMPTY.
if sum(str_Index_A)>0 && sum(str_Index_B)>0 
    out_Index_str = str_Index_A;
    out_Index_str(str_Index_A)=ismember(A(str_Index_A),B(str_Index_B));
else 
    out_Index_str = false(size(A,1),size(A,2));
end
if sum(num_Index_A)>0 && sum(num_Index_B)>0 
    out_Index_num = num_Index_A;
    out_Index_num(num_Index_A)=ismember(cell2mat(A(num_Index_A)),cell2mat(B(num_Index_B)));
else 
    out_Index_num = false(size(A,1),size(A,2));
end
if sum(NaN_Index_A)>0 && sum(NaN_Index_B)>0 
    out_Index_NaN = NaN_Index_A;
else 
    out_Index_NaN = false(size(A,1),size(A,2));
end
if sum(empty_Index_A)>0 && sum(empty_Index_B)>0 
    out_Index_empty = empty_Index_A;
else 
    out_Index_empty = false(size(A,1),size(A,2));
end
Lia = out_Index_str  | out_Index_num | out_Index_NaN | out_Index_empty;
end %end of cellismember

%%
%location_excel='\\wi-files1\jain_lab\Pushkal\Results\Second Run increased\601\O'; %Whole image data, but keep a single plate file 
%location_excel_cell='\\wi-files1\jain_lab\Pushkal\Results\Second Run increased\601\O'; %Object data but keep a single plate file
%ds_excel=tabularTextDatastore(location_excel,'FileExtensions','.csv');
%ds_excel_cell=tabularTextDatastore(location_excel_cell,'FileExtensions','.csv');
%Data=readall(ds_excel);
%Data_cell=readall(ds_excel_cell);
%[a,b]=size(Data);  %a is the total number of images in the excel files in the folder
%Number_of_images=a;  %Number of images in the plate ~ 384*10
%stack_data={Data};   %stack_data is a cell whose every element is a plate
%stack_data_cell={Data_cell};   %stack_data is a cell whose every element is a single plate

%%
% Calculate number of wells in the plate  
% data_for_each_image=stack_data_cell{1,1}; 
% well_unique=unique(data_for_each_image.Metadata_Well);
% Number_of_wells=length(well_unique); 

% Calculate YFP/mCherry ratio for all images %Take YFP/mCherry ratio for
% all images and put in "ratio" vector where each element is one image
% 
%    data_for_each_image=stack_data{1,1};
%    number_nuclei=data_for_each_image.Count_Nucleus;
%    ratio=data_for_each_image.Intensity_TotalIntensity_Processed_YFP./data_for_each_image.Intensity_TotalIntensity_Processed_mCherry;
%    well_index=data_for_each_image.Metadata_Well;
% 
% 
% %Also nullify any images with <10 nuclei or >700 nuclei (change based on
% objective used, good for 10X)
% 
%    for j=1:length(number_nuclei)
%        record=zeros(j);
%       if number_nuclei(j)<10 || number_nuclei(j)>700
%           record(j)=1;
%       end
%    end
%        number_nuclei(record>0)=[]; ratio(record>0)=[];
%        well_index(record>0)=[];


%% Calculation of mean and STD for each well in a single plate
% 
% 
% %Find unique wells and take mean/STD over them
% well_unique=unique(well_index);
% 
% for j=1:length(well_unique)
%      index=find(contains(well_index,well_unique(j)));
%      image_ratio(j)=mean(ratio(index)); image_stdev(j)=std(ratio(index));
%      image_nuclei_number(j)=mean(number_nuclei(index));
%      image_nuclei_std(j)=std(number_nuclei(index));
%      image_well_index(j)=well_unique(j);
% end

%Plot error bars
 
% errorbarxy(image_nuclei_number,image_ratio,image_nuclei_std,image_stdev);
% 
% dx = 0.1; dy = 0.1; % displacement so the text does not overlay the data
% points text(image_nuclei_number+dx, image_ratio+dy,image_well_index);



